{
 "title": "Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "messagesQueue",
    "label": "Messages queue",
    "query": "query_result(rabbitmq_queue_messages{queue=~\"node.*\"} > 0)"
   },
   {
    "name": "processedQueue",
    "label": "Published & acknowledged queue",
    "query": "query_result(rate(rabbitmq_queue_messages_published_total{queue=~\"node.*\"}[1m]) > 0 or rate(rabbitmq_channel_messages_acked_total{queue=~\"node.*\"}[1m]) > 0)"
   }
  ]
 },
 "panels": [
  {
   "title": "Messages in $messagesQueue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=~\"$messagesQueue\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Published per second in $processedQueue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(rabbitmq_queue_messages_published_total{queue=~\"$processedQueue\"}[1m])",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Acknowledged per second in $processedQueue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(rabbitmq_channel_messages_acked_total{queue=~\"$processedQueue\"}[1m])",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Published in $processedQueue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_published_total{queue=~\"$processedQueue\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Acknowledged in $processedQueue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rabbitmq_channel_messages_acked_total{queue=~\"$processedQueue\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  }
 ]
}