version: '3.5'
services:

    worker:
        image: worker-sdk:tag
        build: ./docker
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www
        volumes:
            - ./:/var/www:cached
        environment:
            # Envs for tests are load from .jest/testEnvs.js
            JEST_DOCKER: 1
            APP_ENV: 'debug'
            CRYPT_SECRET: 'ThisIsNotSoSecret'
            BACKEND_URL: 'http://127.0.0.42:8080'
            STARTING_POINT_DSN: 'http://127.0.0.42:8080'
            WORKER_API_HOST: 'http://127.0.0.42:8080'
            ORCHESTY_API_KEY: 'ThisIsNotSoSecretApiKey'
            MONGODB_DSN: 'mongodb://127.0.0.42:27017/webinars'
        command: sleep infinity

    db:
        image: mysql:5
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wpuser
            MYSQL_PASSWORD: wpuser
            MYSQL_ROOT_PASSWORD: root
        ports:
            - ${DEV_IP}:3306:3306

    redis:
        image: redis:alpine
        ports:
            - ${DEV_IP}:6379:6379

    mongo:
        image: mongo
        ports:
            - ${DEV_IP}:27017:27017
        volumes:
            - mongodb:/data/db

volumes:
    mongodb:
